<?php
return [
    'user' => [
        'name' => 'Alex Hartman',
        'email' => 'alex.h@email.com',
        'avatar' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuAMAZhQeV3BqlKJFxQ2RUeoHFmmOzFxKChX7UWIAKjUHI2Us8awbZ1rFBHaRmNpj_f_JnRN5v9dDbG0dlt5Ap5AitmOGCrnODK6bXmt89rjSNcSopUNdbUMW5DnMMrNogykaiAKH7kl9uMEIBmLcVLG7ShqohJjjzqNhfPtVZOR0c9lAn-DnxX4rr1KtqznnUQSnmEOl1Pq9_7vCEu2QSCh8C5bG-b_U7SrJVKtVooum46eKSlw1dMAC-FYecW4zeGyu2Zm28lBN2UP',
        'plan' => 'Pro Creator',
        'location' => 'Berlin, Germany',
        'joined' => 'Jan 2024',
    ],
    'nav_links' => [
        ['slug' => 'dashboard', 'label' => 'Dashboard', 'icon' => 'dashboard', 'href' => 'dashboard.php'],
        ['slug' => 'purchases', 'label' => 'Purchased Items', 'icon' => 'shopping_cart', 'href' => 'purchases.php'],
        ['slug' => 'downloads', 'label' => 'Downloads', 'icon' => 'download', 'href' => 'downloads.php'],
        ['slug' => 'favorites', 'label' => 'Favorites', 'icon' => 'favorite', 'href' => 'favorites.php'],
        ['slug' => 'profile', 'label' => 'Profile', 'icon' => 'person', 'href' => 'profile.php'],
        ['slug' => 'billing', 'label' => 'Billing', 'icon' => 'receipt_long', 'href' => 'billing.php'],
        ['slug' => 'support', 'label' => 'Support', 'icon' => 'support_agent', 'href' => 'support.php'],
    ],
    'overview_stats' => [
        ['label' => 'Lifetime Spend', 'value' => '$1,248.00', 'subtext' => '+12% vs last year'],
        ['label' => 'Total Purchases', 'value' => '18', 'subtext' => 'Across 5 categories'],
        ['label' => 'Active Downloads', 'value' => '42', 'subtext' => 'Tokens expire in 2h'],
        ['label' => 'Support Tickets', 'value' => '2 open', 'subtext' => 'Avg response 1h'],
    ],
    'purchases' => [
        [
            'title' => 'Astra Pro Theme',
            'category' => 'WordPress Theme',
            'seller' => 'ThemeMasters',
            'purchased_at' => 'Oct 26, 2025',
            'price_usd' => 59,
            'price_ngn' => 88000,
            'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuAg_7pkPaIhNbDM7E-xHk2yBNJay_lslma1Y0iGBmUcWw0Q9CWwvzNpjWM45Gtpleb-eSFW40yOVmBUUBdx_qMZDAeDcKS3DiNuQsH8fUkWvDCSeRKmqgi0_2F9WEMsZm3QcFbfXOmyIJctL0gAU4JpWc5-SKkjwK3ZLouDhSddMyJy0N-BO1wxZ6q2AmayL8XfieNOmkZbNbhXMUZCk0XKrccu7o0CfEI9jRgZ7qIbUOsMgZUjWXpHx601K3vXbCtLuoHAmdEFsZKW',
            'download_url' => 'downloads.php?token=astra-pro',
            'details_url' => '#order-astra',
        ],
        [
            'title' => 'Quantum UI Kit',
            'category' => 'UI Kit',
            'seller' => 'DesignSphere',
            'purchased_at' => 'Sep 15, 2025',
            'price_usd' => 49,
            'price_ngn' => 73000,
            'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuDZuPH22ZSw_hzm5WJm1aOsR8o8qSad9R9eOf-TeulPbM41YcbXJAos5icIWALl8khSUGDVzJF_tdam_O4cGbeiIfmQ8cCCfHTmqIZXKIPE7OrHwWYSyCHSXlYGV-1cp7YSMiEjGlde6PyfBl9zwFA5vprvqzcmEWj7Y5JOV3r44eo3KoNQ-l-6rRuXlcyySC52w_nhLiCCJBWsd8qz7cMhQ5kPwMDGyV9sJ52M_hNKjHOPn21jw5z1-19bmiSv1hELvg2zCKAAEcGq',
            'download_url' => 'downloads.php?token=quantum-kit',
            'details_url' => '#order-quantum',
        ],
        [
            'title' => 'Chirp Social App',
            'category' => 'Mobile App Source',
            'seller' => 'AppWizards',
            'purchased_at' => 'Aug 02, 2025',
            'price_usd' => 120,
            'price_ngn' => 179000,
            'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuBGPDbbefKECrcELIfjmnuzO8kVC2JYTbkVSsWn2tZxIh57nFs2aFSLwQbQO9tk5Z6xB8l7Q4zaOPue17nA1eO4HkrAn9II1KYQDV2mDnQ6dLLo0rpPdAf-af0cuLm7rb7j9DwJckSVsr28WjKli4_XIQQiksPb6ekFmkR8vriZ9oPJfseDWmCVbE-jaTUvzW8eVLobn65lXtlW56OwfP8Uk8ctJRwBIVIWm2_lihJufIw5suG3eb6_SkrJR551sAnWSC177UDkyQ_p',
            'download_url' => 'downloads.php?token=chirp-app',
            'details_url' => '#order-chirp',
        ],
        [
            'title' => 'Formify Pro',
            'category' => 'Plugin',
            'seller' => 'CodeCrafters',
            'purchased_at' => 'Jul 21, 2025',
            'price_usd' => 29,
            'price_ngn' => 43000,
            'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuDvIdaLeLaDG2H4YUR9ovNdNdicVUEw1Snt-wi3FnCIVkAlLM9wVNEK-fZPUvIMkunnlvaBIpIiJNK5bEZzhtOP9NtfiIoVxnLDNRqwldkKGmlDYOTAdWEGGXQQB7a5F64H_aPrw6WvFkkD0IhGs9h-gDZ81eq4g0GiGKJMIMAMpqvZxJuBsuUQBGn7qVzJjljoVbB03xJUYx3pDPY2rLm69wuJ-mKcCFxFo_6MsxTVf1YQOeRorCvUssgWNHubFasxnydSApLsJkEe',
            'download_url' => 'downloads.php?token=formify',
            'details_url' => '#order-formify',
        ],
    ],
    'downloads' => [
        [
            'title' => 'Futura UI Kit',
            'category' => 'UI Kit',
            'note' => 'Instant download',
            'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuBQfaXUtrUgkI8O675SiWOZdkiqGBS6xR2Ezi00CvznHf248M-KoxCT-ly5LXGqNjyQaBBp3YLFol15yPBIe77OcNmK6RVuEWPCXBHeTWVjbA7ifMen5lFuffJsfrBBuSZ6ZnVK_GgEvaI6PdHh3lL1AkZD3_V9ZoZW7COnZ0hdIAjn4zsfQZ4kTdiaPwSCo_kDdLEZism-YmIW8e18HcsIX0MDTA9seBnhDJ-bGDh9T7Xy3BYu6LvuvRiD3pFn_rNWQ-l-QNUGWf4D',
            'download_url' => 'downloads.php?token=futura',
            'status' => 'Ready',
        ],
        [
            'title' => 'NeoBlock Theme',
            'category' => 'WordPress Theme',
            'note' => 'Instant download',
            'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuDDU2sZbYKe9QiSmgknF80BWo8LGONovK3qZQsPjOJFuJNisvEGe7TEdIg1R1X0FNolVd54Oakv4ipXgHtg9H0oMKoYJbRqgFCidxs-49K3NhQgImiJH1S7RzrVqX6RgOqINOOHDUuFGu5hvS0KPCihCIUxWQPL7eEee085ecWAKGqa5BnCBQ-0qP1SPlXBSXnjmn-4f_65z6wqOTvta0PwmR9fneechuqJfD09S8TICU0Gw1hnuLhTZB5N7KLRbiPDu0UH5bJ9ScEE',
            'download_url' => 'downloads.php?token=neoblock',
            'status' => 'Ready',
        ],
        [
            'title' => 'DataViz Script',
            'category' => 'Website Script',
            'note' => 'Instant download',
            'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuDlyd_g7Gfmq74txdfmcigSysWl1lOOTjz7IkSk2wuN_8kkf5g_DCFfY_Ed1XdFzSKMKqJ2FJh93NLQEXS1eMlDBeNv82kx-ZpVABRywtQl8KV1MYMjo-wFxATzN5opmbdZnbVd1A1gBKoDwnFiC_nQ-IXK6xImxjw5RUTsuuYvxFhM8krP6_0RbtIWQHvxvfcHexEdIWgiENy-vZnYhFcn1Qm98lNB-tw2DU3Zdt_ZlCO7o5KuUOEcSvgSgJ-1Qdq9TXpzhoC2OQk5',
            'download_url' => 'downloads.php?token=dataviz',
            'status' => 'Ready',
        ],
        [
            'title' => 'TaskFlow App Code',
            'category' => 'Mobile App',
            'note' => 'Instant download',
            'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuAlC8Aj-KjbXt0AblzMkOjkuBHr29WB-kZpxg1sH13bZtOqj_8xqdUnh7f_KN4YQSEeRQ7VEcfmX4Wy05grAQFcvlBXH6EUIHKyEKHMzenaC2wmk--sdDbzzhsn6gqzoWNtqooPWhZedkVRNaMsU3dPb90NF8-rkHPOtgPCpsO8sVEeTcG4lOJIsCtwSWFRrMaw-FQ8uN1tOQJXP_qo34kRTBVThju8L4UZA6clYuklJwDy3sVyIlrb6DsLIbWTSeDLfTo1YceBUPxW',
            'download_url' => 'downloads.php?token=taskflow',
            'status' => 'Ready',
        ],
    ],
    'favorites' => [
        [
            'title' => 'Nova Dashboard Kit',
            'category' => 'UI Kit',
            'rating' => 4.9,
            'price_usd' => 42,
            'tags' => ['Figma', 'Light + Dark'],
            'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuCp6lW373wZNNafjHuxjPA3mTN9Uy5EezEJ1C0K7o1VlEpjKnpowZYQmUu_T0TQUP39xlNt9VuVNcOXKuUDD-1Q26AYfXvbxDqedERu0e4ZAntT9VWq5wztW2VaEjVXbFRFmdZVb_zpoz8Kp5zV0FMlSkmVQk0m5i4mnNm8ukTTfWBSi8TTnao-FkGAGlrICVS9DPA8aqyGPk0ZbQv_E1OGB66B4ruQpZgdLFgKn8J7bampum-fcqX1sxW4YSzHPiaD7KXJ8Q3w0874',
        ],
        [
            'title' => 'Pulse Analytics Template',
            'category' => 'SaaS Template',
            'rating' => 4.8,
            'price_usd' => 65,
            'tags' => ['Tailwind', 'Charts'],
            'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuBCGoMu4UlcFswhoWtuBbA091YnbdVip5126-SpfXQ0TGkLR7maWS8jgurg1CvskFXyYDIUKkxKi8MUE3DOdgn0H02_t0OCQslo0rEbJulTvjlYzJVq2nKAjzHha77eqicnb4WC8M_wgPbKzJDE1aojpnDcAejh20RIJo5emzQRmVR-OF0XBqHEWZIO0OwToZ5JKGObjsRGDUZ50U8JynQyWKSmLt35YhZj4pHFDwGmuPwJKx9PyAkq4MNhOa3uj0-k0A4hSzDaKx5D',
        ],
        [
            'title' => 'Checkout Motion Pack',
            'category' => 'After Effects',
            'rating' => 4.7,
            'price_usd' => 35,
            'tags' => ['Animations'],
            'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuAfc0VDtkNppTY6nRzlM2uKS5HVc5XHF4t1DE9oTTgPuYZ6pRq_xflGLyD6U_2vQye08z8TTBRjq1LitlLeww4JXnLCSJ8hpsewSlSa41xR4opTs_K7Mrb5cS1B7eua_STQkIOCndKjkbFuOUVk3TiZzh7m0u7awCjgA6u67I4YdIe670M8DdAkFtU9Ut4rHsp-Accn0q5RS7dt0uleGXVbU-k7fz992ES9O8yMxbNP5MUVp_27bCqXIk6YKK9Et-oMaGN-8z5ejJcf',
        ],
        [
            'title' => 'SynthWave Landing',
            'category' => 'Website Template',
            'rating' => 5.0,
            'price_usd' => 38,
            'tags' => ['Next.js', 'Framer Motion'],
            'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuAMjZHM5c4NnOzHW-zKLJMh14uWXYvQKpZ3tZ_JjJAzNQYGmwgic0UTFX3x61ePjq0UlptCSzbaPFNEQuL--6VJ1RMYBiNOuNDa2h3fYAEgTj8kujhEt0qWCv_r62VgM2PUia9wr7j9Blfj1fSZhm_ma_h-5cl1UNhAYNhJGLnemsJgtnzLWvtGP6hXdxKOzjtgSg_ai9BK6hXxRD_N22jUh8jAJF9tu27o8qsHWg2wji2oGD3VXskA82Or0QIZIA8z8Vqub7WGPVm',
        ],
    ],
    'billing_methods' => [
        ['brand' => 'Visa', 'last4' => '1234', 'exp' => '08/26', 'is_primary' => true],
        ['brand' => 'Mastercard', 'last4' => '5678', 'exp' => '11/24', 'is_primary' => false],
    ],
    'invoices' => [
        ['id' => 'INV-2048', 'date' => 'Nov 02, 2025', 'amount' => '$59.00', 'status' => 'Paid', 'download_url' => '#inv-2048'],
        ['id' => 'INV-2037', 'date' => 'Oct 15, 2025', 'amount' => '$120.00', 'status' => 'Paid', 'download_url' => '#inv-2037'],
        ['id' => 'INV-1994', 'date' => 'Sep 09, 2025', 'amount' => '$49.00', 'status' => 'Paid', 'download_url' => '#inv-1994'],
    ],
    'notification_preferences' => [
        ['key' => 'product_updates', 'label' => 'Product updates & patches', 'description' => 'Get notified when your purchases receive a new release.', 'enabled' => true],
        ['key' => 'promotions', 'label' => 'Marketplace promotions', 'description' => 'Occasional curated drops and seasonal bundles.', 'enabled' => false],
        ['key' => 'security', 'label' => 'Security alerts', 'description' => 'Login attempts, password changes, download token events.', 'enabled' => true],
    ],
    'support_tickets' => [
        ['id' => '#4521', 'subject' => 'Download access issue', 'status' => 'Open', 'updated_at' => '2h ago', 'priority' => 'Medium'],
        ['id' => '#4499', 'subject' => 'Download token expired', 'status' => 'In Progress', 'updated_at' => '5h ago', 'priority' => 'High'],
        ['id' => '#4410', 'subject' => 'Payment receipt copy', 'status' => 'Resolved', 'updated_at' => 'Oct 28, 2025', 'priority' => 'Low'],
    ],
];
